name: Notifier

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  notifyTelegram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Telegram notification 
        uses: appleboy/telegram-action@master 
        with:
          to: "6997724786"
          token: "6997724786:AAFXhOAnpJ2u3afEZSqQXCG01LWyy3fapq4"
          message: "New push to master branch in your GitHub repository."